name: Code check

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
  workflow_dispatch:

permissions:
  pull-requests: read
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint . --quiet

      - name: Run Prettier
        run: npx prettier --check .
